//= lib/svgxuse.min.js
//= lib/smoothscroll.js
//= ../../bower_components/fullpage.js/jquery.fullPage.min.js

// = lib/jquery-ui.min.js
// = lib/jquery.parallax.js
// = lib/imagesloaded.pkgd.min.js
// = lib/anime.min.js
// = lib/scrollMonitor.js
// = lib/bootstrap.min.js
// = ../../bower_components/jquery-background-video/jquery.background-video.js
// = lib/bootstrap.min.js
// = lib/jquery.fancybox.min.js
// = ../../bower_components/jquery-ui/ui/widget.js
// = ../../bower_components/jquery-ui/ui/keycode.js
// = ../../bower_components/jquery-ui/ui/effect.js
// = ../../bower_components/jquery-ui/ui/widgets/mouse.js
// = ../../bower_components/jquery-ui/ui/widgets/slider.js
// = ../../bower_components/jquery-ui/ui/effects/effect-slide.js
